version: '3'

services:
  app:
    image: t0k0sh1/twitty_authservice:latest
    environment:
      NODE_ENV: development
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: testdb
      DB_HOST: mysql
      JWT_SECRET_KEY: "123456789"
    depends_on:
      - mysql
    ports:
      - 3000:80
  # MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment: 
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on: 
      - mysql
    ports:
      - 8080:80